[build]
base = "/"

publish = "dist/cinemafun/browser"

[context.deploy-preview]
publish = "dist/cinemafun/browser"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[images]
remote_images = [
    "https://cinemafun.netlify.app",
    "https://cinemafun.netlify.app/.*",
    "https://api.themoviedb.org/3/*",
    "https://image.tmdb.org/t/p/*",
    "https://image.tmdb.org/t/p/.*",
]
